 * Restarting DNS forwarder and DHCP server dnsmasq
   ...done.
[Modelarts Service Log][decrypt_modelarts_aes_env_by_key_client] export AWS_SECRET_ACCESS_KEY
[Modelarts Service Log]user: uid=1101(work) gid=1101(work) groups=1101(work)
[Modelarts Service Log]pwd: /home/work
[Modelarts Service Log]app_url: s3://my-obs-cn-north1/aifood-train/aifood/
[Modelarts Service Log]boot_file: aifood/main.py
[Modelarts Service Log]log_url: /tmp/log/trainjob-3792.log
[Modelarts Service Log]command: aifood/main.py --data_url=s3://my-obs-cn-north1/aifood/ --init_method=tcp://job52055208-job-trainjob-3792-0:6666 --train_url=s3://my-obs-cn-north1/aifood-train/aifood/model/
[Modelarts Service Log]MODELARTS_IPOIB_DEVICE: 
[Modelarts Service Log]dependencies_file_dir: /home/work/user-job-dir/aifood
[Modelarts Service Log][modelarts_create_log] modelarts-pipe found
INFO:root:Using MoXing-v1.13.0-de803ac9
INFO:root:Using OBS-Python-SDK-3.1.2
[ModelArts Service Log]2019-09-11 20:53:53,958 - modelarts-downloader.py[line:548] - INFO: Main: modelarts-downloader starting with Namespace(dst='./', recursive=True, src='s3://my-obs-cn-north1/aifood-train/aifood/', trace=False, verbose=False)
[ModelArts Service Log]2019-09-11 20:53:54,028 - ilog.py[line:127] - WARNING: obsclient|initLog,305|[OBS SDK Version=3.1.2];[Endpoint=https://obs.myhuaweicloud.com:443];[Access Mode=Virtual Hosting]
/home/work/user-job-dir
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
INFO:root:Using MoXing-v1.13.0-de803ac9
INFO:root:Using OBS-Python-SDK-3.1.2
Traceback (most recent call last):
  File "aifood/main.py", line 79, in <module>
    main()
  File "aifood/main.py", line 39, in main
    mox.file.copy_parallel(args.data_url, datapath)
NameError: name 'mox' is not defined
